// src/lib/sentry/sentry.constants.ts

export const SENTRY_DSN_PUBLIC_ENV = 'NEXT_PUBLIC_SENTRY_DSN';
export const SENTRY_ENVIRONMENT_PUBLIC_ENV = 'NEXT_PUBLIC_SENTRY_ENVIRONMENT';
export const SENTRY_RELEASE_PUBLIC_ENV = 'NEXT_PUBLIC_SENTRY_RELEASE';
export const SENTRY_TRACES_RATE_PUBLIC_ENV = 'NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE';
export const SENTRY_DSN_SERVER_ENV = 'SENTRY_DSN_WEB';
